import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import * as XLSX from 'xlsx'

export async function POST(request) {
  try {
    const { month, email,filename } = await request.json()

    const supabaseAdmin = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    )

    // Build date range
    const [year, monthNum] = month.split('-')
    const startDate = `${year}-${monthNum}-01`
    const lastDay = new Date(year, monthNum, 0).getDate()
    const endDate = `${year}-${monthNum}-${lastDay}`

    // Fetch all time records for the month
    const { data: records, error } = await supabaseAdmin
      .from('time_records')
      .select('*, staff:profiles!time_records_staff_id_fkey(full_name, email, branch:branches(name))')
      .gte('clock_in', startDate)
      .lte('clock_in', endDate + 'T23:59:59')
      .not('clock_out', 'is', null)
      .order('clock_in')

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 })
    }

    // Build summary per staff
    const summaryMap = {}
    const detailRows = []

    records.forEach(function(r) {
      const name = r.staff?.full_name || 'Unknown'
      const email = r.staff?.email || ''
      const branch = r.staff?.branch?.name || 'Main Branch'
      const hours = r.total_minutes ? (r.total_minutes / 60).toFixed(2) : '0'
      const clockIn = new Date(r.clock_in).toLocaleString('en-GB')
      const clockOut = r.clock_out ? new Date(r.clock_out).toLocaleString('en-GB') : '-'

      // Summary
      if (!summaryMap[name]) {
        summaryMap[name] = { name, email, branch, totalMinutes: 0, shifts: 0 }
      }
      summaryMap[name].totalMinutes += r.total_minutes || 0
      summaryMap[name].shifts += 1

      // Detail row
      detailRows.push({
        'Staff Name': name,
        'Branch': branch,
        'Clock In': clockIn,
        'Clock Out': clockOut,
        'Hours Worked': parseFloat(hours),
        'Notes': r.notes || ''
      })
    })

    // Summary rows
    const summaryRows = Object.values(summaryMap).map(function(s) {
      return {
        'Staff Name': s.name,
        'Email': s.email,
        'Branch': s.branch,
        'Total Shifts': s.shifts,
        'Total Hours': parseFloat((s.totalMinutes / 60).toFixed(2)),
        'Total Minutes': s.totalMinutes
      }
    })

    // Create workbook with two sheets
    const workbook = XLSX.utils.book_new()

    // Sheet 1 — Summary
    const summarySheet = XLSX.utils.json_to_sheet(summaryRows)
    summarySheet['!cols'] = [
      { wch: 25 }, { wch: 30 }, { wch: 20 },
      { wch: 15 }, { wch: 15 }, { wch: 15 }
    ]
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary')

    // Sheet 2 — Detailed records
    const detailSheet = XLSX.utils.json_to_sheet(detailRows)
    detailSheet['!cols'] = [
      { wch: 25 }, { wch: 20 }, { wch: 22 },
      { wch: 22 }, { wch: 15 }, { wch: 30 }
    ]
    XLSX.utils.book_append_sheet(workbook, detailSheet, 'Detailed Records')

    // Convert to base64 buffer
    const excelBuffer = XLSX.write(workbook, { type: 'base64', bookType: 'xlsx' })

    // Format month label
    const monthLabel = new Date(year, monthNum - 1).toLocaleString('en-GB', {
      month: 'long', year: 'numeric'
    })

    // Send email with attachment via Resend
    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'Restaurant System <onboarding@resend.dev>',
        to: email,
        subject: `Staff Work Hours Report — ${monthLabel}`,
        html: `
          <h2>Staff Work Hours Report</h2>
          <p>Please find attached the staff work hours report for <strong>${monthLabel}</strong>.</p>
          <h3>Summary</h3>
          <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;">
            <tr style="background:#f3f4f6">
              <th>Staff Name</th>
              <th>Branch</th>
              <th>Total Shifts</th>
              <th>Total Hours</th>
            </tr>
            ${summaryRows.map(function(r) {
              return `<tr>
                <td>${r['Staff Name']}</td>
                <td>${r['Branch']}</td>
                <td>${r['Total Shifts']}</td>
                <td>${r['Total Hours']}</td>
              </tr>`
            }).join('')}
          </table>
          <p style="color:#6b7280;font-size:12px;margin-top:24px;">
            Generated by Restaurant System
          </p>
        `,
        attachments: [
          {
            filename: (fileName || 'staff-report') + '-' + month + '.xlsx',
            content: excelBuffer
          }
        ]
      })
    })

    const resendData = await resendResponse.json()

    if (!resendResponse.ok) {
      console.log('Email error:', resendData)
      return NextResponse.json({
        success: false,
        warning: 'Report generated but email failed: ' + (resendData.message || 'Unknown error'),
        excel: excelBuffer
      })
    }

    return NextResponse.json({
      success: true,
      excel: excelBuffer,
      summary: summaryRows
    })

  } catch (error) {
    console.log('Report error:', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}